EXEC      = minisat-incre-simp
DEPDIR    = mtl utils mod simp 
MROOT     = /home/umass/Dropbox/Research-w-Prof-H/ReverseEngineeringProj/Our-papers/deobfuscation/Experiment-Scripts/Decamouflage/minisat-mod
include $(MROOT)/mtl/template.mk
